Building DAG of jobs...
Using shell: /usr/bin/bash
Provided cores: 1
Rules claiming more threads will be scaled down.
Job counts:
	count	jobs
	3	kallisto_quant
	1	sleuth
	4

[Thu Jan 10 14:47:13 2019]
rule kallisto_quant:
    input: kallisto/transcripts.idx, data/reads/b.chr21.1.fq, data/reads/b.chr21.2.fq
    output: kallisto/b
    jobid: 3
    wildcards: sample=b

kallisto quant -i kallisto/transcripts.idx -o  kallisto/b data/reads/b.chr21.1.fq data/reads/b.chr21.2.fq
[Thu Jan 10 14:47:13 2019]
Finished job 3.
1 of 4 steps (25%) done

[Thu Jan 10 14:47:13 2019]
rule kallisto_quant:
    input: kallisto/transcripts.idx, data/reads/a.chr21.1.fq, data/reads/a.chr21.2.fq
    output: kallisto/a
    jobid: 2
    wildcards: sample=a

kallisto quant -i kallisto/transcripts.idx -o  kallisto/a data/reads/a.chr21.1.fq data/reads/a.chr21.2.fq
[Thu Jan 10 14:47:13 2019]
Finished job 2.
2 of 4 steps (50%) done

[Thu Jan 10 14:47:13 2019]
rule kallisto_quant:
    input: kallisto/transcripts.idx, data/reads/a.chr21.1.fq, data/reads/a.chr21.2.fq
    output: kallisto/c
    jobid: 4
    wildcards: sample=c

kallisto quant -i kallisto/transcripts.idx -o  kallisto/c data/reads/a.chr21.1.fq data/reads/a.chr21.2.fq
[Thu Jan 10 14:47:14 2019]
Finished job 4.
3 of 4 steps (75%) done

[Thu Jan 10 14:47:14 2019]
rule sleuth:
    input: kallisto/a, kallisto/b, kallisto/c, kallisto/d, table_for_reads.csv
    output: sleuth/significant_transcripts.csv
    jobid: 0

Rscript /home/sattle00/Fachprojekt/fprdg1/.snakemake/scripts/tmpb1o4s_uh.sleuth_script.R
[Thu Jan 10 14:47:15 2019]
Error in rule sleuth:
    jobid: 0
    output: sleuth/significant_transcripts.csv

RuleException:
CalledProcessError in line 37 of /home/sattle00/Fachprojekt/fprdg1/Snakefile:
Command ' set -euo pipefail;  Rscript /home/sattle00/Fachprojekt/fprdg1/.snakemake/scripts/tmpb1o4s_uh.sleuth_script.R ' returned non-zero exit status 1.
  File "/home/sattle00/Fachprojekt/fprdg1/Snakefile", line 37, in __rule_sleuth
  File "/home/sattle00/miniconda3/envs/fprdg1/lib/python3.6/concurrent/futures/thread.py", line 56, in run
Shutting down, this might take some time.
Exiting because a job execution failed. Look above for error message
Complete log: /home/sattle00/Fachprojekt/fprdg1/.snakemake/log/2019-01-10T144712.809820.snakemake.log
